# -*- coding: utf-8 -*-
"""
utils/email_sender.py — PDF email delivery after successful Stripe payment.

Supports three backends (auto-detected from env vars, in priority order):
  1. SendGrid  — SENDGRID_API_KEY
  2. Resend    — RESEND_API_KEY
  3. SMTP      — EMAIL_SMTP_HOST + EMAIL_SMTP_PORT + EMAIL_SMTP_USER + EMAIL_SMTP_PASS

If none are configured → logs a warning and returns False (never raises).

Usage:
    from utils.email_sender import send_pdf_by_email

    ok = await send_pdf_by_email(
        to_email="user@example.com",
        pdf_path="/path/to/anmeldung_final.pdf",
        doc_type="anmeldung",
        lang="uk",
    )
"""

import os
import logging
import asyncio
from typing import Optional

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Optional dependency availability flags
# ---------------------------------------------------------------------------

try:
    import resend  # noqa: F401
    RESEND_AVAILABLE = True
except ImportError:
    RESEND_AVAILABLE = False

# ---------------------------------------------------------------------------
# Official form links per doc_type
# ---------------------------------------------------------------------------

_OFFICIAL_LINKS: dict = {
    "anmeldung":                     "https://www.bundesregierung.de/breg-de/service/buergerinformation/anmeldung-beim-einwohnermeldeamt-1763774",
    "ummeldung":                     "https://www.bundesregierung.de/breg-de/service/buergerinformation/ummeldung-1763812",
    "abmeldung":                     "https://www.bundesregierung.de/breg-de/service/buergerinformation/abmeldung-beim-einwohnermeldeamt-1763844",
    "wohnungsgeberbestaetigung":     "https://www.gesetze-im-internet.de/bmg/__19.html",
    "mietbescheinigung":             "https://www.mietrechtsinfo.de/mietbescheinigung/",
    "beschaeftigungserklaerung":     "https://www.arbeitsagentur.de/datei/erklaerung-arbeitgeber_ba013484.pdf",
    "wohngeld":                      "https://www.bmi.bund.de/DE/themen/stadtentwicklung/wohnen/wohngeld/wohngeld-node.html",
    "kindergeld":                    "https://www.kindergeld.org/",
    "buergergeld":                   "https://www.arbeitsagentur.de/buergergeld",
    "aufenthaltstitel":              "https://www.bamf.de/DE/Themen/MigrationAufenthalt/migrationaufenthalt-node.html",
    "verlaengerung_aufenthaltstitel": "https://www.bamf.de/DE/Themen/MigrationAufenthalt/migrationaufenthalt-node.html",
    "bafoeg":                        "https://www.bafög.de/",
    "elterngeld":                    "https://www.elterngeld.net/",
    "unterhaltsvorschuss":           "https://www.bmfsfj.de/bmfsfj/themen/familie/familienleistungen/unterhaltsvorschuss",
}

_DEFAULT_OFFICIAL_LINK = "https://www.deutschland.de/de/topic/buerger"

# ---------------------------------------------------------------------------
# Localized email subjects
# ---------------------------------------------------------------------------

_SUBJECT: dict = {
    "uk": "CivicAssistBot — Ваш документ готовий",
    "en": "CivicAssistBot — Your document is ready",
    "de": "CivicAssistBot — Ihr Dokument ist fertig",
    "pl": "CivicAssistBot — Twój dokument jest gotowy",
    "tr": "CivicAssistBot — Belgeniz hazır",
    "ar": "CivicAssistBot — المستند جاهز",
}

# ---------------------------------------------------------------------------
# Localized email content blocks
# ---------------------------------------------------------------------------

_HTML_L10N: dict = {
    "en": {
        "status_badge":      "Your document is ready",
        "greeting":          "Hello,",
        "intro":             "Your document <strong>{doc_label}</strong> has been successfully generated and is attached to this email.",
        "disclaimer_title":  "Important Notice",
        "disclaimer_body":   (
            "This is <strong>NOT</strong> an official document. "
            "It is a filled-in sample designed to help you correctly complete the official government form. "
            "You must transfer the data into the official form before submission."
        ),
        "steps_title":       "What to do next:",
        "step1":             "Use this as a reference",
        "step2":             "Transfer the data into the official form",
        "step3":             "Submit the official document to the authority",
        "official_btn":      "Open official form",
        "support_intro":     "Questions? Contact us on Telegram:",
        "support_cta":       "AI Support",
        "footer_legal":      (
            "This document was generated by CivicAssistBot for informational and "
            "reference purposes only. It is not a substitute for official government forms."
        ),
        "attachment_note":   "The file is attached to this email.",
    },
    "de": {
        "status_badge":      "Ihr Dokument ist fertig",
        "greeting":          "Hallo,",
        "intro":             "Ihr Dokument <strong>{doc_label}</strong> wurde erfolgreich erstellt und ist dieser E-Mail beigefügt.",
        "disclaimer_title":  "Wichtiger Hinweis",
        "disclaimer_body":   (
            "Dies ist <strong>KEIN</strong> offizielles Dokument. "
            "Es ist ein ausgefülltes Beispiel, das Ihnen hilft, das offizielle Formular korrekt auszufüllen. "
            "Bitte übertragen Sie die Daten in das offizielle Formular, bevor Sie es einreichen."
        ),
        "steps_title":       "Was als Nächstes zu tun ist:",
        "step1":             "Als Vorlage verwenden",
        "step2":             "Daten in das offizielle Formular übertragen",
        "step3":             "Offizielles Dokument bei der Behörde einreichen",
        "official_btn":      "Offizielles Formular öffnen",
        "support_intro":     "Fragen? Kontaktieren Sie uns auf Telegram:",
        "support_cta":       "KI-Support",
        "footer_legal":      (
            "Dieses Dokument wurde von CivicAssistBot nur zu Informations- und Referenzzwecken erstellt. "
            "Es ersetzt keine offiziellen Behördenformulare."
        ),
        "attachment_note":   "Die Datei ist dieser E-Mail beigefügt.",
    },
    "uk": {
        "status_badge":      "Ваш документ готовий",
        "greeting":          "Вітаємо,",
        "intro":             "Ваш документ <strong>{doc_label}</strong> успішно створено та прикріплено до цього листа.",
        "disclaimer_title":  "Важливо",
        "disclaimer_body":   (
            "Це <strong>НЕ</strong> офіційний документ. "
            "Це заповнений зразок для правильного оформлення офіційного бланка. "
            "Перенесіть дані до офіційного бланка перед поданням."
        ),
        "steps_title":       "Що робити далі:",
        "step1":             "Використовуйте як зразок",
        "step2":             "Перенесіть дані до офіційного бланка",
        "step3":             "Подайте офіційний документ до відповідного органу",
        "official_btn":      "Відкрити офіційний бланк",
        "support_intro":     "Є питання? Зв'яжіться з нами у Telegram:",
        "support_cta":       "ШІ-підтримка",
        "footer_legal":      (
            "Цей документ створено CivicAssistBot виключно в інформаційних та довідкових цілях. "
            "Він не замінює офіційні державні бланки."
        ),
        "attachment_note":   "Файл прикріплено до цього листа.",
    },
    "pl": {
        "status_badge":      "Twój dokument jest gotowy",
        "greeting":          "Witaj,",
        "intro":             "Twój dokument <strong>{doc_label}</strong> został wygenerowany i jest załączony do tej wiadomości.",
        "disclaimer_title":  "Ważna informacja",
        "disclaimer_body":   (
            "To <strong>NIE</strong> jest oficjalny dokument. "
            "To przykład pomagający poprawnie wypełnić oficjalny formularz urzędowy. "
            "Przed złożeniem przenieś dane do oficjalnego formularza."
        ),
        "steps_title":       "Co zrobić dalej:",
        "step1":             "Użyj jako wzoru",
        "step2":             "Przenieś dane do oficjalnego formularza",
        "step3":             "Złóż oficjalny dokument w urzędzie",
        "official_btn":      "Otwórz oficjalny formularz",
        "support_intro":     "Pytania? Skontaktuj się z nami na Telegramie:",
        "support_cta":       "Wsparcie AI",
        "footer_legal":      (
            "Dokument wygenerowany przez CivicAssistBot wyłącznie do celów informacyjnych. "
            "Nie zastępuje oficjalnych formularzy urzędowych."
        ),
        "attachment_note":   "Plik jest załączony do tej wiadomości.",
    },
    "tr": {
        "status_badge":      "Belgeniz hazır",
        "greeting":          "Merhaba,",
        "intro":             "Belgeniz <strong>{doc_label}</strong> başarıyla oluşturuldu ve bu e-postaya eklenmiştir.",
        "disclaimer_title":  "Önemli Uyarı",
        "disclaimer_body":   (
            "Bu resmi bir belge <strong>DEĞİLDİR</strong>. "
            "Resmi formu doğru doldurmak için hazırlanmış örnek bir belgedir. "
            "Başvurmadan önce verileri resmi forma aktarın."
        ),
        "steps_title":       "Sonraki adımlar:",
        "step1":             "Referans olarak kullanın",
        "step2":             "Verileri resmi forma aktarın",
        "step3":             "Resmi belgeyi ilgili makama teslim edin",
        "official_btn":      "Resmi formu aç",
        "support_intro":     "Sorularınız mı var? Telegram'dan bizimle iletişime geçin:",
        "support_cta":       "Yapay Zeka Desteği",
        "footer_legal":      (
            "Bu belge CivicAssistBot tarafından yalnızca bilgilendirme amacıyla oluşturulmuştur. "
            "Resmi devlet formlarının yerini tutmaz."
        ),
        "attachment_note":   "Dosya bu e-postaya eklenmiştir.",
    },
    "ar": {
        "status_badge":      "المستند جاهز",
        "greeting":          "مرحبًا،",
        "intro":             "تم إنشاء مستندك <strong>{doc_label}</strong> بنجاح وهو مرفق بهذا البريد الإلكتروني.",
        "disclaimer_title":  "ملاحظة مهمة",
        "disclaimer_body":   (
            "هذا <strong>ليس</strong> مستندًا رسميًا. "
            "إنه نموذج مملوء للمساعدة في تعبئة النموذج الرسمي بشكل صحيح. "
            "يجب نقل البيانات إلى النموذج الرسمي قبل تقديمه."
        ),
        "steps_title":       "ماذا تفعل بعد ذلك:",
        "step1":             "استخدمه كمرجع",
        "step2":             "انقل البيانات إلى النموذج الرسمي",
        "step3":             "قدّم المستند الرسمي إلى الجهة المختصة",
        "official_btn":      "فتح النموذج الرسمي",
        "support_intro":     "هل لديك أسئلة؟ تواصل معنا على Telegram:",
        "support_cta":       "دعم الذكاء الاصطناعي",
        "footer_legal":      (
            "تم إنشاء هذا المستند بواسطة CivicAssistBot لأغراض المعلومات والمرجعية فقط. "
            "لا يُغني عن النماذج الحكومية الرسمية."
        ),
        "attachment_note":   "الملف مرفق بهذا البريد الإلكتروني.",
    },
}

# ---------------------------------------------------------------------------
# Doc display labels
# ---------------------------------------------------------------------------

_DOC_LABELS: dict = {
    "anmeldung":                     {"uk": "Анмельдунг", "en": "Anmeldung", "de": "Anmeldung", "pl": "Anmeldung", "tr": "Anmeldung", "ar": "Anmeldung"},
    "ummeldung":                     {"uk": "Уммельдунг", "en": "Ummeldung", "de": "Ummeldung", "pl": "Ummeldung", "tr": "Ummeldung", "ar": "Ummeldung"},
    "abmeldung":                     {"uk": "Абмельдунг", "en": "Abmeldung", "de": "Abmeldung", "pl": "Abmeldung", "tr": "Abmeldung", "ar": "Abmeldung"},
    "wohnungsgeberbestaetigung":     {"uk": "Підтвердження квартирного власника", "en": "Landlord confirmation", "de": "Wohnungsgeberbest.", "pl": "Potwierdzenie wynajmującego", "tr": "Ev sahibi onayı", "ar": "تأكيد المالك"},
    "mietbescheinigung":             {"uk": "Орендна довідка", "en": "Rental certificate", "de": "Mietbescheinigung", "pl": "Zaświadczenie najmu", "tr": "Kira belgesi", "ar": "شهادة الإيجار"},
    "beschaeftigungserklaerung":     {"uk": "Заява про зайнятість", "en": "Employment declaration", "de": "Beschäftigungserklärung", "pl": "Deklaracja zatrudnienia", "tr": "İstihdam beyanı", "ar": "إقرار التوظيف"},
    "wohngeld":                      {"uk": "Жилова допомога", "en": "Housing benefit", "de": "Wohngeld", "pl": "Dodatek mieszkaniowy", "tr": "Konut yardımı", "ar": "إعانة السكن"},
    "kindergeld":                    {"uk": "Дитяча допомога", "en": "Child benefit", "de": "Kindergeld", "pl": "Zasiłek rodzinny", "tr": "Çocuk parası", "ar": "علاوة الأطفال"},
    "buergergeld":                   {"uk": "Соціальна допомога", "en": "Citizens' benefit", "de": "Bürgergeld", "pl": "Zasiłek obywatelski", "tr": "Vatandaşlık yardımı", "ar": "إعانة المواطنين"},
    "aufenthaltstitel":              {"uk": "Дозвіл на перебування", "en": "Residence permit", "de": "Aufenthaltstitel", "pl": "Zezwolenie na pobyt", "tr": "Oturma izni", "ar": "تصريح الإقامة"},
    "verlaengerung_aufenthaltstitel": {"uk": "Продовження дозволу", "en": "Permit extension", "de": "Verlängerung Aufenthaltstitel", "pl": "Przedłużenie zezwolenia", "tr": "İzin uzatma", "ar": "تمديد التصريح"},
    "bafoeg":                        {"uk": "BAföG", "en": "BAföG", "de": "BAföG", "pl": "BAföG", "tr": "BAföG", "ar": "BAföG"},
    "elterngeld":                    {"uk": "Допомога батькам", "en": "Parental benefit", "de": "Elterngeld", "pl": "Zasiłek rodzicielski", "tr": "Ebeveyn yardımı", "ar": "إعانة الوالدين"},
    "unterhaltsvorschuss":           {"uk": "Аліменти", "en": "Maintenance advance", "de": "Unterhaltsvorschuss", "pl": "Zaliczka alimentacyjna", "tr": "Nafaka avansı", "ar": "سلفة النفقة"},
}


def _get_doc_label(doc_type: str, lang: str) -> str:
    labels = _DOC_LABELS.get((doc_type or "").lower(), {})
    return labels.get(lang) or labels.get("en") or doc_type


def _get_official_link(doc_type: str) -> str:
    return _OFFICIAL_LINKS.get((doc_type or "").lower(), _DEFAULT_OFFICIAL_LINK)


def _get_from_address() -> str:
    return os.environ.get("EMAIL_FROM", "CivicAssistBot <noreply@civicassistbot.com>")


def _get_support_link(doc_type: str = "") -> str:
    bot_username = os.environ.get("BOT_USERNAME", "")
    if bot_username and doc_type:
        return f'https://t.me/{bot_username}?start=ai_{doc_type}'
    if bot_username:
        return f'https://t.me/{bot_username}'
    return os.environ.get("SUPPORT_TELEGRAM", "https://t.me/CivicAssistBot")


# ---------------------------------------------------------------------------
# HTML email builder
# ---------------------------------------------------------------------------

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="{html_lang}" dir="{html_dir}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>CivicAssistBot</title>
</head>
<body style="margin:0;padding:0;background-color:#eef2f7;font-family:Arial,Helvetica,sans-serif;">
<table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="0"
       style="background-color:#eef2f7;">
  <tr>
    <td align="center" style="padding:40px 16px;">

      <!-- CARD -->
      <table role="presentation" width="600" border="0" cellspacing="0" cellpadding="0"
             style="background:#ffffff;border-radius:16px;overflow:hidden;
                    box-shadow:0 4px 24px rgba(0,0,0,0.10);max-width:600px;width:100%;">

        <!-- ══ HEADER ══ -->
        <tr>
          <td style="background:linear-gradient(135deg,#0d1f3c 0%,#1b4db5 100%);
                     padding:36px 40px 28px;text-align:center;">
            <table role="presentation" border="0" cellspacing="0" cellpadding="0"
                   style="margin:0 auto 14px;">
              <tr>
                <td style="width:80px;height:80px;background:rgba(255,255,255,0.12);
                           border-radius:50%;border:2px solid rgba(240,192,64,0.70);
                           text-align:center;vertical-align:middle;font-size:40px;
                           line-height:80px;">&#127963;</td>
              </tr>
            </table>
            <div style="font-size:26px;font-weight:700;color:#ffffff;
                        letter-spacing:1px;margin-bottom:6px;">CivicAssistBot</div>
            <div style="font-size:12px;color:rgba(255,255,255,0.60);letter-spacing:0.4px;">
              Dokumentenhilfe &nbsp;·&nbsp; Document Assistance
            </div>
          </td>
        </tr>

        <!-- ══ STATUS BADGE ══ -->
        <tr>
          <td style="background:#1b4db5;padding:14px 40px;text-align:center;">
            <span style="display:inline-block;background:rgba(255,255,255,0.18);
                         color:#ffffff;font-size:14px;font-weight:600;
                         padding:7px 22px;border-radius:20px;letter-spacing:0.4px;">
              ✅ &nbsp;{status_badge}
            </span>
          </td>
        </tr>

        <!-- ══ BODY ══ -->
        <tr>
          <td style="padding:36px 40px 28px;">

            <p style="margin:0 0 18px;font-size:16px;color:#1a2c4e;font-weight:600;">
              {greeting}
            </p>
            <p style="margin:0 0 24px;font-size:15px;color:#374151;line-height:1.75;">
              {intro}
            </p>

            <!-- DISCLAIMER BOX -->
            <table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="0"
                   style="margin-bottom:24px;">
              <tr>
                <td style="background:#fff8e8;border-left:4px solid #f59e0b;
                           border-radius:0 8px 8px 0;padding:16px 20px;">
                  <div style="font-size:12px;font-weight:700;color:#92400e;
                              text-transform:uppercase;letter-spacing:0.6px;margin-bottom:8px;">
                    ⚠️ &nbsp;{disclaimer_title}
                  </div>
                  <div style="font-size:13px;color:#78350f;line-height:1.65;">
                    {disclaimer_body}
                  </div>
                </td>
              </tr>
            </table>

            <!-- STEPS -->
            <p style="margin:0 0 10px;font-size:14px;font-weight:600;color:#1a2c4e;">
              {steps_title}
            </p>
            <table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="0"
                   style="margin-bottom:28px;">
              <tr>
                <td style="padding:4px 0;">
                  <span style="display:inline-block;width:22px;height:22px;background:#1b4db5;
                               color:#fff;border-radius:50%;text-align:center;line-height:22px;
                               font-size:11px;font-weight:700;margin-right:10px;vertical-align:middle;">1</span>
                  <span style="font-size:14px;color:#374151;vertical-align:middle;">{step1}</span>
                </td>
              </tr>
              <tr><td style="height:6px;"></td></tr>
              <tr>
                <td style="padding:4px 0;">
                  <span style="display:inline-block;width:22px;height:22px;background:#1b4db5;
                               color:#fff;border-radius:50%;text-align:center;line-height:22px;
                               font-size:11px;font-weight:700;margin-right:10px;vertical-align:middle;">2</span>
                  <span style="font-size:14px;color:#374151;vertical-align:middle;">{step2}</span>
                </td>
              </tr>
              <tr><td style="height:6px;"></td></tr>
              <tr>
                <td style="padding:4px 0;">
                  <span style="display:inline-block;width:22px;height:22px;background:#1b4db5;
                               color:#fff;border-radius:50%;text-align:center;line-height:22px;
                               font-size:11px;font-weight:700;margin-right:10px;vertical-align:middle;">3</span>
                  <span style="font-size:14px;color:#374151;vertical-align:middle;">{step3}</span>
                </td>
              </tr>
            </table>

            <!-- OFFICIAL LINK BUTTON -->
            <table role="presentation" border="0" cellspacing="0" cellpadding="0"
                   style="margin-bottom:28px;">
              <tr>
                <td style="border-radius:8px;background:#1b4db5;">
                  <a href="{official_link}"
                     style="display:inline-block;padding:12px 28px;font-size:14px;
                            font-weight:600;color:#ffffff;text-decoration:none;
                            letter-spacing:0.3px;">
                    {official_btn} &rarr;
                  </a>
                </td>
              </tr>
            </table>

            <!-- SUPPORT -->
            <p style="margin:0;font-size:14px;color:#6b7280;line-height:1.7;">
              {support_intro}
              <a href="{support_href}" style="color:#1b4db5;font-weight:600;
                                              text-decoration:none;">{support_cta}</a>
            </p>

          </td>
        </tr>

        <!-- ══ DIVIDER ══ -->
        <tr>
          <td style="padding:0 40px;">
            <hr style="border:none;border-top:1px solid #e5e7eb;margin:0;">
          </td>
        </tr>

        <!-- ══ ATTACHMENT NOTE ══ -->
        <tr>
          <td style="padding:16px 40px;background:#f8fafc;">
            <table role="presentation" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td style="vertical-align:middle;padding-right:10px;font-size:20px;">&#128206;</td>
                <td style="vertical-align:middle;font-size:13px;color:#6b7280;">
                  <strong style="color:#374151;">{doc_label}</strong>
                  &nbsp;&mdash;&nbsp;{attachment_note}
                </td>
              </tr>
            </table>
          </td>
        </tr>

        <!-- ══ FOOTER ══ -->
        <tr>
          <td style="background:#f1f5f9;padding:22px 40px;text-align:center;">
            <p style="margin:0 0 6px;font-size:12px;font-weight:600;color:#64748b;">
              CivicAssistBot
            </p>
            <p style="margin:0;font-size:11px;color:#94a3b8;line-height:1.6;max-width:480px;margin:0 auto;">
              {footer_legal}
            </p>
          </td>
        </tr>

      </table><!-- /CARD -->
    </td>
  </tr>
</table>
</body>
</html>
"""


def _build_html_email(
    lang: str,
    doc_label: str,
    official_link: str,
    support_href: str,
) -> str:
    """Build the complete branded HTML email for the given language."""
    l10n = _HTML_L10N.get(lang) or _HTML_L10N["en"]
    html_dir = "rtl" if lang == "ar" else "ltr"
    html_lang = lang if lang != "ua" else "uk"

    return _HTML_TEMPLATE.format(
        html_lang=html_lang,
        html_dir=html_dir,
        status_badge=l10n["status_badge"],
        greeting=l10n["greeting"],
        intro=l10n["intro"].format(doc_label=doc_label),
        disclaimer_title=l10n["disclaimer_title"],
        disclaimer_body=l10n["disclaimer_body"],
        steps_title=l10n["steps_title"],
        step1=l10n["step1"],
        step2=l10n["step2"],
        step3=l10n["step3"],
        official_link=official_link,
        official_btn=l10n["official_btn"],
        support_intro=l10n["support_intro"],
        support_href=support_href,
        support_cta=l10n["support_cta"],
        doc_label=doc_label,
        attachment_note=l10n["attachment_note"],
        footer_legal=l10n["footer_legal"],
    )


# ---------------------------------------------------------------------------
# Plain-text fallback
# ---------------------------------------------------------------------------

def _build_plain_email(lang: str, doc_label: str, official_link: str) -> str:
    """Plain text fallback for email clients that don't render HTML."""
    l10n = _HTML_L10N.get(lang) or _HTML_L10N["en"]
    import re
    _strip = lambda s: re.sub(r'<[^>]+>', '', s)
    return (
        f"CivicAssistBot\n"
        f"{'=' * 40}\n\n"
        f"{l10n['greeting']}\n\n"
        f"{_strip(l10n['intro'].format(doc_label=doc_label))}\n\n"
        f"{'─' * 40}\n"
        f"{l10n['disclaimer_title'].upper()}\n"
        f"{_strip(l10n['disclaimer_body'])}\n"
        f"{'─' * 40}\n\n"
        f"{l10n['steps_title']}\n"
        f"1. {l10n['step1']}\n"
        f"2. {l10n['step2']}\n"
        f"3. {l10n['step3']}\n\n"
        f"{l10n['official_btn']}: {official_link}\n\n"
        f"CivicAssistBot"
    )


# ---------------------------------------------------------------------------
# Backend: SendGrid
# ---------------------------------------------------------------------------

def _send_via_sendgrid(
    to_email: str,
    subject: str,
    body_html: str,
    body_plain: str,
    pdf_path: str,
    pdf_filename: str,
) -> bool:
    try:
        import sendgrid
        from sendgrid.helpers.mail import (
            Mail, Attachment, FileContent, FileName,
            FileType, Disposition,
        )
        import base64

        api_key = os.environ["SENDGRID_API_KEY"]
        sg = sendgrid.SendGridAPIClient(api_key=api_key)

        with open(pdf_path, "rb") as f:
            pdf_data = base64.b64encode(f.read()).decode()

        attachment = Attachment(
            FileContent(pdf_data),
            FileName(pdf_filename),
            FileType("application/pdf"),
            Disposition("attachment"),
        )
        message = Mail(
            from_email=_get_from_address(),
            to_emails=to_email,
            subject=subject,
            html_content=body_html,
            plain_text_content=body_plain,
        )
        message.attachment = attachment
        sg.send(message)
        logger.info("EMAIL_SENDGRID_SENT: to=%s file=%s", to_email, pdf_filename)
        return True
    except Exception as e:
        logger.warning("EMAIL_SENDGRID_FAILED: to=%s err=%s", to_email, e)
        return False


# ---------------------------------------------------------------------------
# Backend: Resend
# ---------------------------------------------------------------------------

def _send_via_resend(
    to_email: str,
    subject: str,
    body_html: str,
    pdf_path: str,
    pdf_filename: str,
) -> bool:
    if not RESEND_AVAILABLE:
        logger.error(
            "EMAIL_PROVIDER_ERROR: provider=resend missing_module=True "
            "— install with: pip install resend"
        )
        return False

    _api_key = os.getenv("RESEND_API_KEY", "")
    logger.info("RESEND_API_KEY_PRESENT=%s", bool(_api_key))
    if not _api_key:
        logger.error("EMAIL_SEND_ERROR: RESEND_API_KEY is not set — cannot send email")
        return False

    try:
        import resend
        import base64

        resend.api_key = _api_key

        with open(pdf_path, "rb") as f:
            pdf_data = base64.b64encode(f.read()).decode()

        logger.info("EMAIL_SEND_START resend to=%s file=%s size=%d", to_email, pdf_filename, len(pdf_data))

        response = resend.Emails.send({
            "from": _get_from_address(),
            "to": [to_email],
            "subject": subject,
            "html": body_html,
            "attachments": [{
                "filename": pdf_filename,
                "content": pdf_data,
            }],
        })

        logger.info("RESEND_RESPONSE=%s", response)
        logger.info("EMAIL_SEND_SUCCESS resend to=%s file=%s", to_email, pdf_filename)
        return True

    except Exception as e:
        logger.error("EMAIL_SEND_ERROR resend to=%s err=%s", to_email, e)
        return False


# ---------------------------------------------------------------------------
# Backend: SMTP (stdlib — no extra dependencies)
# ---------------------------------------------------------------------------

def _send_via_smtp(
    to_email: str,
    subject: str,
    body_html: str,
    body_plain: str,
    pdf_path: str,
    pdf_filename: str,
) -> bool:
    try:
        import smtplib
        from email.mime.multipart import MIMEMultipart
        from email.mime.text import MIMEText
        from email.mime.application import MIMEApplication

        host = os.environ["EMAIL_SMTP_HOST"]
        port = int(os.environ.get("EMAIL_SMTP_PORT", "587"))
        user = os.environ["EMAIL_SMTP_USER"]
        password = os.environ["EMAIL_SMTP_PASS"]
        # For SMTP the From address must match the authenticated account (Gmail strict).
        # Use the SMTP user directly; fall back to EMAIL_FROM only for custom servers.
        _smtp_from_env = _get_from_address()
        if "gmail.com" in host.lower() or _smtp_from_env in ("onboarding@resend.dev",):
            from_addr = f"CivicAssistBot <{user}>"
        else:
            from_addr = _smtp_from_env

        logger.info("SMTP_CONFIG host=%s port=%s user=%s from=%s", host, port, user, from_addr)

        _attach_size = os.path.getsize(pdf_path) if os.path.exists(pdf_path) else 0
        logger.info("ATTACHMENT_PATH=%s exists=%s size=%d", pdf_path, os.path.exists(pdf_path), _attach_size)

        msg = MIMEMultipart("mixed")
        msg["Subject"] = subject
        msg["From"] = from_addr
        msg["To"] = to_email

        # Multipart/alternative: HTML + plain text
        alt = MIMEMultipart("alternative")
        alt.attach(MIMEText(body_plain, "plain", "utf-8"))
        alt.attach(MIMEText(body_html, "html", "utf-8"))
        msg.attach(alt)

        with open(pdf_path, "rb") as f:
            part = MIMEApplication(f.read(), _subtype="pdf")
            part.add_header("Content-Disposition", "attachment", filename=pdf_filename)
            msg.attach(part)

        with smtplib.SMTP(host, port, timeout=10) as server:
            server.ehlo()
            server.starttls()
            server.ehlo()
            server.login(user, password)
            try:
                server.send_message(msg)
            except Exception as _smtp_send_err:
                logger.error("EMAIL_FAILED_FULL=%s", repr(_smtp_send_err))
                raise

        logger.info("EMAIL_SMTP_SENT: to=%s file=%s host=%s", to_email, pdf_filename, host)
        return True
    except Exception as e:
        logger.error("EMAIL_FAILED: %s", repr(e))
        return False


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def _send_pdf_sync(
    to_email: str,
    pdf_path: str,
    doc_type: str,
    lang: str,
    extra_note: str = "",
) -> bool:
    """Synchronous PDF email delivery. Auto-selects backend from env vars."""
    _lang = "uk" if lang in ("ua", "uk") else lang
    if _lang not in _HTML_L10N:
        _lang = "en"

    doc_label    = _get_doc_label(doc_type, _lang)
    official_link = _get_official_link(doc_type)
    support_href  = _get_support_link(doc_type)

    subject    = _SUBJECT.get(_lang, _SUBJECT["en"])
    body_html  = _build_html_email(_lang, doc_label, official_link, support_href)
    body_plain = _build_plain_email(_lang, doc_label, official_link)
    if extra_note:
        body_plain += f"\n\n{extra_note}"

    pdf_filename = f"{doc_type}_filled.pdf"

    # Priority: SendGrid → Resend (with SMTP fallback) → SMTP
    if os.environ.get("SENDGRID_API_KEY"):
        return _send_via_sendgrid(to_email, subject, body_html, body_plain, pdf_path, pdf_filename)

    if os.environ.get("RESEND_API_KEY"):
        if not RESEND_AVAILABLE:
            logger.warning(
                "EMAIL_PROVIDER_ERROR: provider=resend missing_module=True "
                "— RESEND_API_KEY is set but the resend package is not installed. "
                "Falling back to SMTP if configured."
            )
            if os.environ.get("EMAIL_SMTP_HOST"):
                logger.info("EMAIL_RESEND_FALLBACK_SMTP: resend unavailable, attempting SMTP")
                return _send_via_smtp(to_email, subject, body_html, body_plain, pdf_path, pdf_filename)
            logger.warning(
                "EMAIL_DELIVERY_IMPOSSIBLE: provider=resend missing_module=True "
                "and no SMTP fallback configured — email not sent to %s", to_email
            )
            return False
        _resend_ok = _send_via_resend(to_email, subject, body_html, pdf_path, pdf_filename)
        if _resend_ok:
            return True
        # Resend failed (e.g. unverified domain) — try SMTP fallback if configured
        if os.environ.get("EMAIL_SMTP_HOST") and os.environ.get("EMAIL_SMTP_PASS"):
            logger.warning(
                "EMAIL_RESEND_FAILED_SMTP_FALLBACK: to=%s — Resend failed, trying SMTP", to_email
            )
            return _send_via_smtp(to_email, subject, body_html, body_plain, pdf_path, pdf_filename)
        return False

    if os.environ.get("EMAIL_SMTP_HOST") and os.environ.get("EMAIL_SMTP_PASS"):
        return _send_via_smtp(to_email, subject, body_html, body_plain, pdf_path, pdf_filename)

    logger.warning(
        "EMAIL_NOT_CONFIGURED: no SENDGRID_API_KEY / RESEND_API_KEY / EMAIL_SMTP_HOST set — "
        "skipping email delivery for %s", to_email
    )
    return False


async def send_pdf_by_email(
    to_email: str,
    pdf_path: str,
    doc_type: str,
    lang: str = "en",
    extra_note: str = "",
) -> bool:
    """
    Async wrapper — runs sync email delivery in a thread pool so it never
    blocks the event loop.

    Returns True on success, False on any failure (never raises).
    """
    from utils.lang import normalize_lang
    lang = normalize_lang(lang)

    if not to_email or "@" not in to_email:
        logger.debug("EMAIL_SKIP: invalid or empty email address %r", to_email)
        return False

    if not pdf_path or not os.path.exists(pdf_path):
        logger.warning("EMAIL_SKIP: PDF file not found at %r", pdf_path)
        return False

    try:
        import functools
        loop = asyncio.get_event_loop()
        result = await asyncio.wait_for(
            loop.run_in_executor(
                None,
                functools.partial(_send_pdf_sync, to_email, pdf_path, doc_type, lang, extra_note),
            ),
            timeout=30.0,
        )
        return result
    except asyncio.TimeoutError:
        logger.warning("EMAIL_TIMEOUT: to=%s — provider did not respond within 30s", to_email)
        return False
    except Exception as e:
        logger.warning("EMAIL_UNEXPECTED_ERROR: to=%s err=%s", to_email, e)
        return False


def send_test_email(to_email: str) -> bool:
    """
    Send a plain-text probe email via the configured SMTP backend.

    Called once on bot startup (non-blocking, never raises).
    Helps detect misconfigured credentials before the first real payment.
    """
    _host = os.environ.get("EMAIL_SMTP_HOST", "")
    _user = os.environ.get("EMAIL_SMTP_USER", "")
    _pass = os.environ.get("EMAIL_SMTP_PASS", "")
    _port = int(os.environ.get("EMAIL_SMTP_PORT", "587"))

    if not (_host and _user and _pass):
        logger.info(
            "EMAIL_TEST_SKIP: SMTP not configured (host=%r user=%r) — skipping probe",
            _host, _user,
        )
        return False

    logger.info("EMAIL_TEST_START to=%s host=%s port=%s user=%s", to_email, _host, _port, _user)
    try:
        import smtplib
        from email.mime.text import MIMEText

        msg = MIMEText("CivicAssistBot SMTP probe — delivery confirmed.", "plain", "utf-8")
        msg["Subject"] = "CivicAssistBot — SMTP test"
        msg["From"] = _get_from_address()
        msg["To"] = to_email

        with smtplib.SMTP(_host, _port, timeout=10) as server:
            server.ehlo()
            server.starttls()
            server.ehlo()
            server.login(_user, _pass)
            server.send_message(msg)

        logger.info("EMAIL_TEST_SUCCESS to=%s", to_email)
        return True
    except Exception as e:
        logger.error("EMAIL_TEST_FAILED to=%s error=%s", to_email, repr(e))
        return False


# ---------------------------------------------------------------------------
# Termin slot-found notification
# ---------------------------------------------------------------------------

_TERMIN_SUBJECTS: dict = {
    "en": "Appointment found — book now",
    "de": "Termin gefunden — jetzt buchen",
    "uk": "Знайдено запис — бронюйте зараз",
    "pl": "Znaleziono termin — zarezerwuj teraz",
    "tr": "Randevu bulundu — hemen alın",
    "ar": "تم العثور على موعد — احجز الآن",
}

_TERMIN_L10N: dict = {
    "en": {
        "status_badge":  "Appointment Available Now",
        "greeting":      "Great news!",
        "intro":         "We found an available appointment for your request.",
        "urgent_title":  "Act fast",
        "urgent_body":   "Appointments are limited and may disappear in seconds. Book immediately.",
        "details_title": "Appointment details",
        "city_label":    "City",
        "service_label": "Service",
        "date_label":    "Date",
        "time_label":    "Time",
        "book_btn":      "Book immediately →",
        "footer":        "CivicAssistBot — Appointment Monitoring",
        "dir":           "ltr",
    },
    "de": {
        "status_badge":  "Termin jetzt verfügbar",
        "greeting":      "Gute Nachrichten!",
        "intro":         "Wir haben einen freien Termin für Sie gefunden.",
        "urgent_title":  "Schnell handeln",
        "urgent_body":   "Termine sind begrenzt und können innerhalb von Sekunden verschwinden. Sofort buchen.",
        "details_title": "Termindetails",
        "city_label":    "Stadt",
        "service_label": "Dienstleistung",
        "date_label":    "Datum",
        "time_label":    "Uhrzeit",
        "book_btn":      "Termin sofort buchen →",
        "footer":        "CivicAssistBot — Terminüberwachung",
        "dir":           "ltr",
    },
    "uk": {
        "status_badge":  "Запис тепер доступний",
        "greeting":      "Чудові новини!",
        "intro":         "Ми знайшли доступний запис для вашого запиту.",
        "urgent_title":  "Дійте швидко",
        "urgent_body":   "Записи обмежені та можуть зникнути за секунди. Бронюйте одразу.",
        "details_title": "Деталі запису",
        "city_label":    "Місто",
        "service_label": "Послуга",
        "date_label":    "Дата",
        "time_label":    "Час",
        "book_btn":      "Забронювати одразу →",
        "footer":        "CivicAssistBot — Моніторинг записів",
        "dir":           "ltr",
    },
    "pl": {
        "status_badge":  "Termin jest teraz dostępny",
        "greeting":      "Świetne wiadomości!",
        "intro":         "Znaleźliśmy dostępny termin dla Twojego zapytania.",
        "urgent_title":  "Działaj szybko",
        "urgent_body":   "Terminy są ograniczone i mogą zniknąć w ciągu sekund. Zarezerwuj natychmiast.",
        "details_title": "Szczegóły terminu",
        "city_label":    "Miasto",
        "service_label": "Usługa",
        "date_label":    "Data",
        "time_label":    "Godzina",
        "book_btn":      "Zarezerwuj natychmiast →",
        "footer":        "CivicAssistBot — Monitoring terminów",
        "dir":           "ltr",
    },
    "tr": {
        "status_badge":  "Randevu Şimdi Mevcut",
        "greeting":      "Harika haber!",
        "intro":         "Talebiniz için uygun bir randevu bulduk.",
        "urgent_title":  "Hızlı davranın",
        "urgent_body":   "Randevular sınırlıdır ve saniyeler içinde kaybolabilir. Hemen rezervasyon yapın.",
        "details_title": "Randevu detayları",
        "city_label":    "Şehir",
        "service_label": "Hizmet",
        "date_label":    "Tarih",
        "time_label":    "Saat",
        "book_btn":      "Hemen rezervasyon yap →",
        "footer":        "CivicAssistBot — Randevu Takibi",
        "dir":           "ltr",
    },
    "ar": {
        "status_badge":  "الموعد متاح الآن",
        "greeting":      "أخبار رائعة!",
        "intro":         "وجدنا موعدًا متاحًا لطلبك.",
        "urgent_title":  "تصرف بسرعة",
        "urgent_body":   "المواعيد محدودة وقد تختفي في ثوانٍ. احجز فوراً.",
        "details_title": "تفاصيل الموعد",
        "city_label":    "المدينة",
        "service_label": "الخدمة",
        "date_label":    "التاريخ",
        "time_label":    "الوقت",
        "book_btn":      "احجز فوراً ←",
        "footer":        "CivicAssistBot — مراقبة المواعيد",
        "dir":           "rtl",
    },
}

_TERMIN_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="{html_lang}" dir="{html_dir}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>CivicAssistBot — Termin</title>
</head>
<body style="margin:0;padding:0;background-color:#eef2f7;font-family:Arial,Helvetica,sans-serif;">
<table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="0"
       style="background-color:#eef2f7;">
  <tr>
    <td align="center" style="padding:40px 16px;">

      <!-- CARD -->
      <table role="presentation" width="600" border="0" cellspacing="0" cellpadding="0"
             style="background:#ffffff;border-radius:16px;overflow:hidden;
                    box-shadow:0 4px 24px rgba(0,0,0,0.10);max-width:600px;width:100%;">

        <!-- ══ HEADER ══ -->
        <tr>
          <td style="background:linear-gradient(135deg,#064e3b 0%,#047857 100%);
                     padding:36px 40px 28px;text-align:center;">
            <table role="presentation" border="0" cellspacing="0" cellpadding="0"
                   style="margin:0 auto 14px;">
              <tr>
                <td style="width:80px;height:80px;background:rgba(255,255,255,0.15);
                           border-radius:50%;border:2px solid rgba(52,211,153,0.70);
                           text-align:center;vertical-align:middle;font-size:40px;
                           line-height:80px;">&#128197;</td>
              </tr>
            </table>
            <div style="font-size:26px;font-weight:700;color:#ffffff;
                        letter-spacing:1px;margin-bottom:6px;">CivicAssistBot</div>
            <div style="font-size:12px;color:rgba(255,255,255,0.60);letter-spacing:0.4px;">
              Terminüberwachung &nbsp;·&nbsp; Appointment Monitoring
            </div>
          </td>
        </tr>

        <!-- ══ URGENT BADGE ══ -->
        <tr>
          <td style="background:#059669;padding:14px 40px;text-align:center;">
            <span style="display:inline-block;background:rgba(255,255,255,0.20);
                         color:#ffffff;font-size:15px;font-weight:700;
                         padding:8px 24px;border-radius:20px;letter-spacing:0.5px;">
              &#128994; &nbsp;{status_badge}
            </span>
          </td>
        </tr>

        <!-- ══ BODY ══ -->
        <tr>
          <td style="padding:36px 40px 28px;">

            <p style="margin:0 0 8px;font-size:18px;color:#064e3b;font-weight:700;">
              {greeting}
            </p>
            <p style="margin:0 0 28px;font-size:15px;color:#374151;line-height:1.75;">
              {intro}
            </p>

            <!-- URGENT BOX -->
            <table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="0"
                   style="margin-bottom:28px;">
              <tr>
                <td style="background:#fef3c7;border-left:4px solid #f59e0b;
                           border-radius:0 8px 8px 0;padding:14px 18px;">
                  <div style="font-size:12px;font-weight:700;color:#92400e;
                              text-transform:uppercase;letter-spacing:0.6px;margin-bottom:6px;">
                    &#9889; &nbsp;{urgent_title}
                  </div>
                  <div style="font-size:13px;color:#78350f;line-height:1.6;">{urgent_body}</div>
                </td>
              </tr>
            </table>

            <!-- DETAILS TABLE -->
            <p style="margin:0 0 12px;font-size:14px;font-weight:700;color:#1a2c4e;">
              {details_title}
            </p>
            <table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="0"
                   style="margin-bottom:28px;border-radius:8px;overflow:hidden;
                          border:1px solid #e5e7eb;">
              <tr style="background:#f8fafc;">
                <td style="padding:10px 16px;font-size:13px;font-weight:600;
                           color:#6b7280;width:35%;border-bottom:1px solid #e5e7eb;">
                  {city_label}
                </td>
                <td style="padding:10px 16px;font-size:14px;color:#111827;
                           border-bottom:1px solid #e5e7eb;">
                  <strong>{city_val}</strong>
                </td>
              </tr>
              <tr>
                <td style="padding:10px 16px;font-size:13px;font-weight:600;
                           color:#6b7280;border-bottom:1px solid #e5e7eb;">
                  {service_label}
                </td>
                <td style="padding:10px 16px;font-size:14px;color:#111827;
                           border-bottom:1px solid #e5e7eb;">
                  {service_val}
                </td>
              </tr>
              {date_row}
              {time_row}
            </table>

            <!-- BOOK BUTTON -->
            {book_btn_html}
            {fallback_link_html}

          </td>
        </tr>

        <!-- ══ FOOTER ══ -->
        <tr>
          <td style="background:#f1f5f9;padding:20px 40px;text-align:center;">
            <p style="margin:0;font-size:12px;font-weight:600;color:#64748b;">{footer}</p>
          </td>
        </tr>

      </table>
    </td>
  </tr>
</table>
</body>
</html>
"""


def _build_termin_html_email(
    lang: str,
    city: str,
    service: str,
    date: str,
    time: str,
    booking_url: str,
    fallback_url: str = "",
) -> str:
    l10n = _TERMIN_L10N.get(lang) or _TERMIN_L10N["en"]

    date_row = (
        f'<tr style="background:#f8fafc;">'
        f'<td style="padding:10px 16px;font-size:13px;font-weight:600;color:#6b7280;'
        f'border-bottom:1px solid #e5e7eb;">{l10n["date_label"]}</td>'
        f'<td style="padding:10px 16px;font-size:14px;color:#111827;'
        f'border-bottom:1px solid #e5e7eb;">{date}</td></tr>'
    ) if date else ""

    time_row = (
        f'<tr>'
        f'<td style="padding:10px 16px;font-size:13px;font-weight:600;color:#6b7280;">'
        f'{l10n["time_label"]}</td>'
        f'<td style="padding:10px 16px;font-size:14px;color:#111827;">{time}</td></tr>'
    ) if time else ""

    book_btn_html = (
        f'<table role="presentation" border="0" cellspacing="0" cellpadding="0">'
        f'<tr><td style="border-radius:8px;background:#059669;">'
        f'<a href="{booking_url}" '
        f'style="display:inline-block;padding:14px 32px;font-size:15px;font-weight:700;'
        f'color:#ffffff;text-decoration:none;letter-spacing:0.3px;">'
        f'{l10n["book_btn"]}</a></td></tr></table>'
    ) if booking_url else ""

    # Fallback portal link — shown only when different from primary
    fallback_link_html = ""
    if fallback_url and fallback_url != booking_url:
        fallback_link_html = (
            f'<p style="margin:12px 0 0;font-size:12px;color:#6b7280;text-align:center;">'
            f'If the button above doesn\'t open, '
            f'<a href="{fallback_url}" style="color:#059669;text-decoration:underline;">'
            f'try the booking portal directly</a>.</p>'
        )

    html_lang = lang if lang != "ua" else "uk"
    return _TERMIN_HTML_TEMPLATE.format(
        html_lang=html_lang,
        html_dir=l10n["dir"],
        status_badge=l10n["status_badge"],
        greeting=l10n["greeting"],
        intro=l10n["intro"],
        urgent_title=l10n["urgent_title"],
        urgent_body=l10n["urgent_body"],
        details_title=l10n["details_title"],
        city_label=l10n["city_label"],
        city_val=city,
        service_label=l10n["service_label"],
        service_val=service,
        date_row=date_row,
        time_row=time_row,
        book_btn_html=book_btn_html,
        fallback_link_html=fallback_link_html,
        footer=l10n["footer"],
    )


def _build_termin_plain(
    lang: str, city: str, service: str, date: str, time: str,
    booking_url: str, fallback_url: str = ""
) -> str:
    l10n = _TERMIN_L10N.get(lang) or _TERMIN_L10N["en"]
    lines = [
        "CivicAssistBot",
        "=" * 40,
        "",
        l10n["greeting"],
        l10n["intro"],
        "",
        f"{l10n['city_label']}: {city}",
        f"{l10n['service_label']}: {service}",
    ]
    if date:
        lines.append(f"{l10n['date_label']}: {date}")
    if time:
        lines.append(f"{l10n['time_label']}: {time}")
    lines += ["", f"{l10n['book_btn']}", booking_url or "(no URL)"]
    if fallback_url and fallback_url != booking_url:
        lines += ["", "If the link above doesn't open, try the portal directly:", fallback_url]
    lines += ["", "CivicAssistBot"]
    return "\n".join(lines)


def _send_termin_sync(
    to_email: str,
    city: str,
    service: str,
    date: str,
    time: str,
    booking_url: str,
    lang: str,
    fallback_url: str = "",
) -> bool:
    """Synchronous termin email. Auto-selects backend from env vars."""
    _lang = "uk" if lang in ("ua", "uk") else lang
    if _lang not in _TERMIN_L10N:
        _lang = "en"

    subject    = _TERMIN_SUBJECTS.get(_lang, _TERMIN_SUBJECTS["en"])
    body_html  = _build_termin_html_email(_lang, city, service, date, time, booking_url, fallback_url)
    body_plain = _build_termin_plain(_lang, city, service, date, time, booking_url, fallback_url)
    from_addr  = _get_from_address()

    # Inline send helpers — no PDF attachment needed
    def _sg():
        try:
            import sendgrid
            from sendgrid.helpers.mail import Mail
            sg = sendgrid.SendGridAPIClient(api_key=os.environ["SENDGRID_API_KEY"])
            msg = Mail(
                from_email=from_addr, to_emails=to_email,
                subject=subject, html_content=body_html,
                plain_text_content=body_plain,
            )
            sg.send(msg)
            return True
        except Exception as e:
            logger.warning("TERMIN_EMAIL_SENDGRID_FAILED: to=%s err=%s", to_email, e)
            return False

    def _rs():
        try:
            import resend
            resend.api_key = os.environ["RESEND_API_KEY"]
            resend.Emails.send({
                "from": from_addr, "to": [to_email],
                "subject": subject, "html": body_html,
            })
            return True
        except Exception as e:
            logger.warning("TERMIN_EMAIL_RESEND_FAILED: to=%s err=%s", to_email, e)
            return False

    def _smtp():
        try:
            import smtplib
            from email.mime.multipart import MIMEMultipart
            from email.mime.text import MIMEText
            host     = os.environ["EMAIL_SMTP_HOST"]
            port     = int(os.environ.get("EMAIL_SMTP_PORT", "587"))
            user     = os.environ["EMAIL_SMTP_USER"]
            password = os.environ["EMAIL_SMTP_PASS"]
            msg = MIMEMultipart("alternative")
            msg["Subject"] = subject
            msg["From"]    = from_addr
            msg["To"]      = to_email
            msg.attach(MIMEText(body_plain, "plain", "utf-8"))
            msg.attach(MIMEText(body_html,  "html",  "utf-8"))
            with smtplib.SMTP(host, port, timeout=15) as server:
                server.ehlo(); server.starttls(); server.login(user, password)
                server.sendmail(from_addr, [to_email], msg.as_bytes())
            return True
        except Exception as e:
            logger.warning("TERMIN_EMAIL_SMTP_FAILED: to=%s err=%s", to_email, e)
            return False

    if os.environ.get("SENDGRID_API_KEY"):
        return _sg()
    if os.environ.get("RESEND_API_KEY") and RESEND_AVAILABLE:
        return _rs()
    if os.environ.get("EMAIL_SMTP_HOST"):
        return _smtp()

    logger.warning(
        "TERMIN_EMAIL_NO_PROVIDER: no email backend configured — skipping termin email to %s. "
        "Set SENDGRID_API_KEY, RESEND_API_KEY, or EMAIL_SMTP_HOST to enable.",
        to_email,
    )
    return False


async def send_termin_email(
    to_email: str,
    city: str,
    service: str,
    date: str = "",
    time: str = "",
    booking_url: str = "",
    lang: str = "en",
    fallback_url: str = "",
) -> bool:
    """
    Send a slot-found notification email for Termin monitoring.

    No attachments — just urgent alert with booking link.
    Returns True on success, False on any failure (never raises).
    """
    from utils.lang import normalize_lang
    lang = normalize_lang(lang)

    if not to_email or "@" not in to_email:
        logger.debug("TERMIN_EMAIL_SKIP: invalid address %r", to_email)
        return False
    try:
        loop = asyncio.get_event_loop()
        result = await loop.run_in_executor(
            None,
            _send_termin_sync,
            to_email, city, service, date, time, booking_url, lang, fallback_url,
        )
        if result:
            logger.info(
                "TERMIN_EMAIL_SENT: to=%s city=%s service=%s date=%s",
                to_email, city, service, date,
            )
        else:
            logger.warning(
                "TERMIN_EMAIL_FAILED: to=%s city=%s service=%s",
                to_email, city, service,
            )
        return result
    except Exception as e:
        logger.warning("TERMIN_EMAIL_UNEXPECTED_ERROR: to=%s err=%s", to_email, e)
        return False
