/**
 * lang-switch.js — complete i18n for all static SEO pages.
 * All translations are defined here — no window.PAGE_TRANSLATIONS needed.
 * Usage: set data-i18n="key" on any element.
 */

const BOT_URL = "https://t.me/DE_PDF_Assistant_bot";

const TRANSLATIONS = {
  en: {
    // Navigation
    nav_home: "Home",
    nav_docs: "Documents",
    nav_termin_menu: "Termin",
    nav_anmeldung: "Anmeldung",
    nav_buergergeld: "Bürgergeld",
    nav_kindergeld: "Kindergeld",
    nav_termin: "Termin Berlin",
    nav_faq: "FAQ",
    nav_about: "About",
    // Hero
    hero_title: "Prepare German documents correctly — <span style='color:#93c5fd'>first time.</span>",
    hero_sub: "PDF tool for Anmeldung, Bürgergeld, Kindergeld and Bürgeramt appointments. In your language.",
    hero_trust: "Used by immigrants across Germany",
    // CTA
    cta_open: "Open Telegram Assistant",
    cta_how: "How it works",
    cta_termin: "Start Termin Monitoring",
    cta_find_termin: "Find Termin →",
    cta_title: "Ready to get started?",
    cta_sub: "Open the Telegram bot — free to try.",
    // Stats
    trust_stat1: "Documents",
    trust_stat2: "Languages",
    trust_stat3: "Found Termins",
    trust_badge: "Trusted by thousands of immigrants in Germany",
    // How it works
    how_title: "How it works",
    how_sub: "Four simple steps — no German required.",
    step1_h: "Choose document", step1_p: "Select from 15+ German documents",
    step2_h: "Fill simple form", step2_p: "Answer guided questions in your language",
    step3_h: "Get filled PDF", step3_p: "Download a completed example instantly",
    step4_h: "Termin monitoring", step4_p: "Optional: 24/7 slot finder for Bürgeramt",
    // Documents
    docs_title: "Supported documents",
    docs_sub: "Click any document to learn more and get a filled example.",
    doc_anmeldung_sub: "Address registration",
    doc_ummeldung_sub: "Re-registration",
    doc_buergergeld_sub: "Social benefits",
    doc_kindergeld_sub: "Child benefit",
    doc_wohngeld_sub: "Housing benefit",
    doc_aufenthaltstitel_sub: "Residence permit",
    doc_familienkasse_sub: "Family benefits office",
    doc_termin_sub: "Bürgeramt slot finder",
    // Why section
    why_title: "Why immigrants use this tool",
    why_sub: "German bureaucracy is complex. We make it manageable.",
    why1_h: "Avoid document rejection", why1_p: "Common errors caught before you submit.",
    why2_h: "Understand complex forms", why2_p: "Plain-language explanation of every field.",
    why3_h: "Prepare before your appointment", why3_p: "Arrive at Bürgeramt with everything ready.",
    why4_h: "Save time finding Termin", why4_p: "24/7 monitoring — get notified in seconds.",
    trust_title: "Thousands of immigrants use this tool",
    trust_sub: "Generate PDF examples and save hours of confusion.",
    // What is section
    what_title: "What is the Telegram Document Assistant?",
    what_text: "This tool generates pre-filled PDF examples of German official documents. No German language skills required.",
    what_li1: "Shows correctly filled example forms",
    what_li2: "Explains which documents you need to bring",
    what_li3: "Shows all required fields for each form",
    what_li4: "Helps you prepare before visiting the Bürgeramt",
    what_li5: "Works in 6 languages — your language",
    what_cta_h: "Try it now — free",
    what_cta_p: "Open the assistant in Telegram and ask about any German document.",
    // Features
    feat_title: "What this tool can do",
    feat_sub: "One tool for all your German paperwork.",
    feat1_h: "Anmeldung example", feat1_p: "Get a correctly filled address registration form.",
    feat2_h: "Bürgergeld application", feat2_p: "Understand and fill the social benefit form.",
    feat3_h: "Kindergeld forms", feat3_p: "Step-by-step child benefit application guide.",
    feat4_h: "Document checklist", feat4_p: "Know exactly what to bring to each appointment.",
    feat5_h: "Termin monitoring", feat5_p: "24/7 automated Bürgeramt slot notifications.",
    feat6_h: "Multilingual support", feat6_p: "Works in Ukrainian, German, English, Polish, Turkish, Arabic.",
    // Pricing
    price_title: "Pricing",
    price_sub: "Pay only for what you need. Start for free.",
    price1_name: "Document PDF Example",
    price1_desc: "Filled example form for any supported document",
    price1_amount: "€4.99",
    price1_note: "per document",
    price1_f1: "Pre-filled PDF example",
    price1_f2: "Downloadable PDF",
    price1_f3: "In your language",
    price1_f4: "Instant delivery",
    price2_name: "Termin Monitoring",
    price2_desc: "24/7 automatic Bürgeramt appointment monitoring",
    price2_badge: "Popular",
    price2_amount: "€4.99",
    price2_note: "per 24 hours",
    price2_f1: "Checks every 30 seconds",
    price2_f2: "Instant Telegram notification",
    price2_f3: "Direct booking link",
    price2_f4: "7-day plan from €14.99",
    price3_name: "Bundle",
    price3_desc: "Document PDF + 24h Termin monitoring together",
    price3_amount: "€7.99",
    price3_note: "best value · +€3 Termin add-on",
    price3_f1: "PDF example included",
    price3_f2: "24h monitoring included",
    price3_f3: "Save vs. buying separately",
    price_cta: "Start in Telegram",
    // Telegram install
    tg_title: "Open the assistant in Telegram",
    tg_sub: "Don't have Telegram? Download it free on any device.",
    tg_android: "Android",
    tg_ios: "iPhone",
    tg_windows: "Windows",
    tg_mac: "macOS",
    tg_web: "Web",
    tg_note: "After installing Telegram, tap \"Open Telegram Assistant\" to start.",
    install_hint: "No Telegram yet? Install it:",
    hero_step1: "1️⃣ Telegram bot opens",
    hero_step2: "2️⃣ Answer a few questions",
    hero_step3: "3️⃣ Receive your filled PDF example",
    // Trust notice
    notice_text: "<strong>Notice:</strong> This tool generates pre-filled PDF examples for reference only. It does not provide legal advice. Always submit official forms from the relevant government website.",
    // Footer
    footer_copy: "© 2026 GermanDocAssist. All rights reserved.",
    footer_disclaimer: "These contents do not constitute legal advice. Only PDF examples are provided.",
    footer_docs: "Documents",
    footer_termin: "Termin",
    footer_legal: "Info",
  },

  de: {
    nav_home: "Start",
    nav_docs: "Dokumente",
    nav_termin_menu: "Termin",
    nav_anmeldung: "Anmeldung",
    nav_buergergeld: "Bürgergeld",
    nav_kindergeld: "Kindergeld",
    nav_termin: "Termin Berlin",
    nav_faq: "FAQ",
    nav_about: "Über uns",
    hero_title: "Deutsche Dokumente richtig ausfüllen — <span style='color:#93c5fd'>beim ersten Mal.</span>",
    hero_sub: "PDF-Tool für Anmeldung, Bürgergeld, Kindergeld und Bürgeramt-Termine. In Ihrer Sprache.",
    hero_trust: "Von Einwanderern in ganz Deutschland genutzt",
    cta_open: "Telegram-Assistent öffnen",
    cta_how: "So funktioniert es",
    cta_termin: "Termin-Monitoring starten",
    cta_find_termin: "Termin finden →",
    cta_title: "Bereit loszulegen?",
    cta_sub: "Telegram-Bot öffnen — kostenlos testen.",
    trust_stat1: "Dokumente",
    trust_stat2: "Sprachen",
    trust_stat3: "Gefundene Termine",
    trust_badge: "Von Tausenden Einwanderern in Deutschland genutzt",
    how_title: "So funktioniert es",
    how_sub: "Vier einfache Schritte — kein Deutsch erforderlich.",
    step1_h: "Dokument wählen", step1_p: "Aus 15+ deutschen Dokumenten wählen",
    step2_h: "Formular ausfüllen", step2_p: "Fragen in Ihrer Sprache beantworten",
    step3_h: "PDF erhalten", step3_p: "Ausgefülltes Beispiel sofort herunterladen",
    step4_h: "Termin-Monitoring", step4_p: "Optional: 24/7 Terminsuche beim Bürgeramt",
    docs_title: "Unterstützte Dokumente",
    docs_sub: "Klicken Sie auf ein Dokument, um mehr zu erfahren.",
    doc_anmeldung_sub: "Adressanmeldung",
    doc_ummeldung_sub: "Ummeldung",
    doc_buergergeld_sub: "Sozialleistungen",
    doc_kindergeld_sub: "Kindergeld",
    doc_wohngeld_sub: "Wohngeld",
    doc_aufenthaltstitel_sub: "Aufenthaltstitel",
    doc_familienkasse_sub: "Familienkasse",
    doc_termin_sub: "Terminsuche Bürgeramt",
    why_title: "Warum Einwanderer dieses Tool nutzen",
    why_sub: "Deutsche Bürokratie ist komplex. Wir machen sie handhabbar.",
    why1_h: "Ablehnung vermeiden", why1_p: "Häufige Fehler vor der Einreichung erkennen.",
    why2_h: "Komplexe Formulare verstehen", why2_p: "Klare Erklärung jedes Feldes.",
    why3_h: "Vorbereitung vor dem Termin", why3_p: "Kommen Sie mit allem Nötigen zum Amt.",
    why4_h: "Zeit sparen bei der Terminsuche", why4_p: "24/7-Überwachung — sofortige Benachrichtigung.",
    trust_title: "Tausende Einwanderer nutzen dieses Tool",
    trust_sub: "PDF-Beispieldokumente generieren und stundenlange Verwirrung vermeiden.",
    what_title: "Was ist der Telegram-Dokument-Assistent?",
    what_text: "Dieses Tool erstellt vorausgefüllte PDF-Beispiele für deutsche Behördenformulare. Keine Deutschkenntnisse erforderlich.",
    what_li1: "Zeigt korrekt ausgefüllte Beispielformulare",
    what_li2: "Erklärt, welche Unterlagen Sie mitbringen müssen",
    what_li3: "Zeigt alle erforderlichen Felder für jedes Formular",
    what_li4: "Hilft bei der Vorbereitung vor dem Bürgeramt-Besuch",
    what_li5: "Funktioniert in 6 Sprachen — Ihrer Sprache",
    what_cta_h: "Jetzt kostenlos ausprobieren",
    what_cta_p: "Öffnen Sie den Assistenten in Telegram und fragen Sie nach jedem deutschen Dokument.",
    feat_title: "Was dieses Tool kann",
    feat_sub: "Ein Werkzeug für den gesamten deutschen Papierkram.",
    feat1_h: "Anmeldung-Beispiel", feat1_p: "Vorausgefülltes Anmeldungsbeispiel erhalten.",
    feat2_h: "Bürgergeld-Antrag", feat2_p: "Sozialleistungsformular verstehen und ausfüllen.",
    feat3_h: "Kindergeld-Formulare", feat3_p: "Schritt-für-Schritt-Anleitung für den Antrag.",
    feat4_h: "Dokumentencheckliste", feat4_p: "Genau wissen, was Sie zum Termin mitbringen.",
    feat5_h: "Termin-Monitoring", feat5_p: "Automatische Benachrichtigung bei freien Terminen.",
    feat6_h: "Mehrsprachiger Support", feat6_p: "Ukrainisch, Deutsch, Englisch, Polnisch, Türkisch, Arabisch.",
    price_title: "Preise",
    price_sub: "Zahlen Sie nur, was Sie brauchen. Kostenlos starten.",
    price1_name: "Dokument PDF-Beispiel",
    price1_desc: "Ausgefülltes Beispielformular für jedes unterstützte Dokument",
    price1_amount: "€4.99",
    price1_note: "pro Dokument",
    price1_f1: "Vorausgefülltes PDF-Beispiel",
    price1_f2: "Herunterladbares PDF",
    price1_f3: "In Ihrer Sprache",
    price1_f4: "Sofortige Lieferung",
    price2_name: "Termin-Monitoring",
    price2_desc: "24/7 automatische Bürgeramt-Terminüberwachung",
    price2_badge: "Beliebt",
    price2_amount: "€4.99",
    price2_note: "pro 24 Stunden",
    price2_f1: "Prüft alle 30 Sekunden",
    price2_f2: "Sofortige Telegram-Benachrichtigung",
    price2_f3: "Direkter Buchungslink",
    price2_f4: "7-Tage-Plan ab €14.99",
    price3_name: "Bundle",
    price3_desc: "Dokument PDF + 24h Termin-Monitoring zusammen",
    price3_amount: "€7.99",
    price3_note: "bestes Preis-Leistung · +€3 Termin",
    price3_f1: "PDF-Beispiel inklusive",
    price3_f2: "24h-Monitoring inklusive",
    price3_f3: "Günstiger als Einzelkauf",
    price_cta: "In Telegram starten",
    tg_title: "Assistenten in Telegram öffnen",
    tg_sub: "Telegram noch nicht installiert? Kostenlos auf jedem Gerät.",
    tg_android: "Android",
    tg_ios: "iPhone",
    tg_windows: "Windows",
    tg_mac: "macOS",
    tg_web: "Web",
    tg_note: "Nach der Installation tippen Sie auf «Telegram-Assistenten öffnen».",
    install_hint: "Telegram noch nicht? Jetzt installieren:",
    hero_step1: "1️⃣ Telegram-Bot öffnet sich",
    hero_step2: "2️⃣ Beantworten Sie einige Fragen",
    hero_step3: "3️⃣ Ausgefülltes PDF-Beispiel erhalten",
    notice_text: "<strong>Hinweis:</strong> Dieses Tool erstellt vorausgefüllte PDF-Beispiele zur Orientierung. Es bietet keine Rechtsberatung im Sinne des RDG. Offizielle Formulare sind bei den zuständigen Behörden einzureichen.",
    footer_copy: "© 2026 GermanDocAssist. Alle Rechte vorbehalten.",
    footer_disclaimer: "Diese Inhalte stellen keine Rechtsberatung dar. Es werden ausschließlich PDF-Beispiele bereitgestellt.",
    footer_docs: "Dokumente",
    footer_termin: "Termin",
    footer_legal: "Info",
  },

  ua: {
    nav_home: "Головна",
    nav_docs: "Документи",
    nav_termin_menu: "Termin",
    nav_anmeldung: "Anmeldung",
    nav_buergergeld: "Bürgergeld",
    nav_kindergeld: "Kindergeld",
    nav_termin: "Termin Берлін",
    nav_faq: "FAQ",
    nav_about: "Про нас",
    hero_title: "Заповнюй німецькі документи правильно — <span style='color:#93c5fd'>з першого разу.</span>",
    hero_sub: "PDF-інструмент для Anmeldung, Bürgergeld, Kindergeld та запису у Bürgeramt. Твоєю мовою.",
    hero_trust: "Використовують іммігранти по всій Німеччині",
    cta_open: "Відкрити Telegram-асистент",
    cta_how: "Як це працює",
    cta_termin: "Запустити моніторинг Termin",
    cta_find_termin: "Знайти Termin →",
    cta_title: "Готовий почати?",
    cta_sub: "Відкрий Telegram-бот — безкоштовно.",
    trust_stat1: "Документів",
    trust_stat2: "Мов",
    trust_stat3: "Знайдено Termin",
    trust_badge: "Тисячі іммігрантів у Німеччині вже використали",
    how_title: "Як це працює",
    how_sub: "Чотири прості кроки — без знання німецької.",
    step1_h: "Обери документ", step1_p: "Вибір з 15+ німецьких документів",
    step2_h: "Заповни форму", step2_p: "Відповідай на запитання своєю мовою",
    step3_h: "Отримай PDF", step3_p: "Завантаж заповнений приклад миттєво",
    step4_h: "Моніторинг Termin", step4_p: "Опціонально: пошук слотів 24/7",
    docs_title: "Підтримувані документи",
    docs_sub: "Натисни на документ, щоб дізнатися більше.",
    doc_anmeldung_sub: "Реєстрація адреси",
    doc_ummeldung_sub: "Перереєстрація",
    doc_buergergeld_sub: "Соціальна допомога",
    doc_kindergeld_sub: "Дитячі виплати",
    doc_wohngeld_sub: "Житлова субсидія",
    doc_aufenthaltstitel_sub: "Посвідка на проживання",
    doc_familienkasse_sub: "Сімейні виплати",
    doc_termin_sub: "Пошук запису у Bürgeramt",
    why_title: "Чому іммігранти обирають цей інструмент",
    why_sub: "Німецька бюрократія складна. Ми робимо її зрозумілою.",
    why1_h: "Уникнути відмови", why1_p: "Поширені помилки виявляються до подачі.",
    why2_h: "Зрозуміти складні форми", why2_p: "Простими словами — що і куди вписувати.",
    why3_h: "Підготуватись до запису", why3_p: "Приходь у Bürgeramt з усім готовим.",
    why4_h: "Заощадити час на Termin", why4_p: "Моніторинг 24/7 — миттєве сповіщення.",
    trust_title: "Тисячі іммігрантів використовують цей інструмент",
    trust_sub: "Згенеруй PDF-зразки документів та заощадь години плутанини.",
    what_title: "Що таке Telegram-асистент для документів?",
    what_text: "Цей інструмент генерує попередньо заповнені PDF-зразки офіційних документів Німеччини. Знання німецької не потрібне.",
    what_li1: "Показує правильно заповнені зразки форм",
    what_li2: "Пояснює, які документи потрібно принести",
    what_li3: "Показує всі необхідні поля кожної форми",
    what_li4: "Допомагає підготуватись до Bürgeramt",
    what_li5: "Працює у 6 мовах — твоєю мовою",
    what_cta_h: "Спробуй зараз — безкоштовно",
    what_cta_p: "Відкрий асистент у Telegram і запитай про будь-який німецький документ.",
    feat_title: "Що вміє цей інструмент",
    feat_sub: "Один інструмент для всіх паперів у Німеччині.",
    feat1_h: "Зразок Anmeldung", feat1_p: "Отримай правильно заповнену форму реєстрації.",
    feat2_h: "Заявка Bürgergeld", feat2_p: "Зрозумій і заповни форму соціальної допомоги.",
    feat3_h: "Форми Kindergeld", feat3_p: "Покрокова інструкція для заявки на дитячу виплату.",
    feat4_h: "Список документів", feat4_p: "Знай точно, що взяти на кожен запис.",
    feat5_h: "Моніторинг Termin", feat5_p: "Автоматичні сповіщення про вільні слоти 24/7.",
    feat6_h: "Підтримка 6 мов", feat6_p: "Українська, Німецька, Англійська, Польська, Турецька, Арабська.",
    price_title: "Ціни",
    price_sub: "Платіть лише за те, що потрібно. Починайте безкоштовно.",
    price1_name: "PDF-приклад документа",
    price1_desc: "Заповнений зразок форми для будь-якого підтримуваного документа",
    price1_amount: "€4.99",
    price1_note: "за документ",
    price1_f1: "Попередньо заповнений PDF-зразок",
    price1_f2: "Завантажуваний PDF",
    price1_f3: "Твоєю мовою",
    price1_f4: "Миттєва доставка",
    price2_name: "Моніторинг Termin",
    price2_desc: "Автоматичний пошук вільних місць у Bürgeramt 24/7",
    price2_badge: "Популярне",
    price2_amount: "€4.99",
    price2_note: "за 24 години",
    price2_f1: "Перевірка кожні 30 секунд",
    price2_f2: "Миттєве сповіщення в Telegram",
    price2_f3: "Пряме посилання на бронювання",
    price2_f4: "7-денний план від €14.99",
    price3_name: "Комплект",
    price3_desc: "PDF-документ + 24 год моніторинг разом",
    price3_amount: "€7.99",
    price3_note: "найкраща ціна · +€3 Termin",
    price3_f1: "PDF-зразок включено",
    price3_f2: "24 год моніторинг включено",
    price3_f3: "Вигідніше ніж окремо",
    price_cta: "Почати в Telegram",
    tg_title: "Відкрити асистент у Telegram",
    tg_sub: "Немає Telegram? Завантажте безкоштовно на будь-який пристрій.",
    tg_android: "Android",
    tg_ios: "iPhone",
    tg_windows: "Windows",
    tg_mac: "macOS",
    tg_web: "Веб",
    tg_note: "Після встановлення Telegram натисни «Відкрити Telegram-асистент».",
    install_hint: "Ще немає Telegram? Встановіть:",
    hero_step1: "1️⃣ Відкриється Telegram-бот",
    hero_step2: "2️⃣ Дайте відповіді на кілька питань",
    hero_step3: "3️⃣ Отримаєте заповнений PDF-зразок",
    notice_text: "<strong>Увага:</strong> Цей інструмент генерує PDF-зразки для орієнтування. Це не юридична консультація і не офіційний державний сервіс. Офіційні форми подавайте через відповідні державні сайти.",
    footer_copy: "© 2026 GermanDocAssist. Всі права захищено.",
    footer_disclaimer: "Ці матеріали не є юридичною консультацією. Надаються виключно PDF-зразки.",
    footer_docs: "Документи",
    footer_termin: "Termin",
    footer_legal: "Інфо",
  },

  pl: {
    nav_home: "Strona główna",
    nav_docs: "Dokumenty",
    nav_termin_menu: "Termin",
    nav_anmeldung: "Anmeldung",
    nav_buergergeld: "Bürgergeld",
    nav_kindergeld: "Kindergeld",
    nav_termin: "Termin Berlin",
    nav_faq: "FAQ",
    nav_about: "O nas",
    hero_title: "Wypełniaj niemieckie dokumenty poprawnie — <span style='color:#93c5fd'>za pierwszym razem.</span>",
    hero_sub: "Narzędzie PDF dla Anmeldung, Bürgergeld, Kindergeld i wizyt w Bürgeramt. W Twoim języku.",
    hero_trust: "Używany przez imigrantów w całych Niemczech",
    cta_open: "Otwórz asystenta Telegram",
    cta_how: "Jak to działa",
    cta_termin: "Uruchom monitoring Termin",
    cta_find_termin: "Znajdź Termin →",
    cta_title: "Gotowy na start?",
    cta_sub: "Otwórz bota Telegram — bezpłatnie.",
    trust_stat1: "Dokumenty",
    trust_stat2: "Języki",
    trust_stat3: "Znalezione terminy",
    trust_badge: "Zaufały nam tysiące imigrantów w Niemczech",
    how_title: "Jak to działa",
    how_sub: "Cztery proste kroki — bez znajomości niemieckiego.",
    step1_h: "Wybierz dokument", step1_p: "Spośród 15+ niemieckich dokumentów",
    step2_h: "Wypełnij formularz", step2_p: "Odpowiadaj na pytania w swoim języku",
    step3_h: "Otrzymaj PDF", step3_p: "Pobierz wypełniony przykład od razu",
    step4_h: "Monitoring Termin", step4_p: "Opcjonalnie: szukanie terminów 24/7",
    docs_title: "Obsługiwane dokumenty",
    docs_sub: "Kliknij dokument, aby dowiedzieć się więcej.",
    doc_anmeldung_sub: "Rejestracja adresu",
    doc_ummeldung_sub: "Zmiana adresu",
    doc_buergergeld_sub: "Świadczenia socjalne",
    doc_kindergeld_sub: "Zasiłek na dziecko",
    doc_wohngeld_sub: "Dofinansowanie mieszkania",
    doc_aufenthaltstitel_sub: "Zezwolenie na pobyt",
    doc_familienkasse_sub: "Urząd ds. rodziny",
    doc_termin_sub: "Wyszukiwarka terminów",
    why_title: "Dlaczego imigranci korzystają z tego narzędzia",
    why_sub: "Niemiecka biurokracja jest skomplikowana. Sprawiamy, że jest łatwiejsza.",
    why1_h: "Unikaj odrzucenia", why1_p: "Najczęstsze błędy wykryte przed złożeniem.",
    why2_h: "Zrozum złożone formularze", why2_p: "Proste wyjaśnienie każdego pola.",
    why3_h: "Przygotuj się przed wizytą", why3_p: "Przyjdź do Bürgeramt w pełni gotowy.",
    why4_h: "Oszczędź czas na Termin", why4_p: "Monitoring 24/7 — natychmiastowe powiadomienie.",
    trust_title: "Tysiące imigrantów korzysta z tego narzędzia",
    trust_sub: "Generuj przykłady PDF i oszczędź godziny zamieszania.",
    what_title: "Czym jest asystent dokumentów Telegram?",
    what_text: "To narzędzie generuje wstępnie wypełnione przykłady PDF oficjalnych dokumentów niemieckich. Znajomość języka niemieckiego nie jest wymagana.",
    what_li1: "Pokazuje poprawnie wypełnione przykładowe formularze",
    what_li2: "Wyjaśnia, jakie dokumenty należy zabrać",
    what_li3: "Pokazuje wszystkie wymagane pola każdego formularza",
    what_li4: "Pomaga przygotować się przed wizytą w Bürgeramt",
    what_li5: "Działa w 6 językach — Twoim języku",
    what_cta_h: "Wypróbuj teraz — za darmo",
    what_cta_p: "Otwórz asystenta w Telegramie i zapytaj o dowolny dokument.",
    feat_title: "Co potrafi to narzędzie",
    feat_sub: "Jedno narzędzie do całej papierkowej roboty w Niemczech.",
    feat1_h: "Przykład Anmeldung", feat1_p: "Otrzymaj poprawnie wypełniony formularz rejestracji.",
    feat2_h: "Wniosek Bürgergeld", feat2_p: "Zrozum i wypełnij formularz świadczeń socjalnych.",
    feat3_h: "Formularze Kindergeld", feat3_p: "Przewodnik krok po kroku dla wniosku o zasiłek.",
    feat4_h: "Lista dokumentów", feat4_p: "Wiedz dokładnie, co zabrać na każdą wizytę.",
    feat5_h: "Monitoring Termin", feat5_p: "Automatyczne powiadomienia o wolnych slotach 24/7.",
    feat6_h: "Wsparcie wielojęzyczne", feat6_p: "Ukraiński, Niemiecki, Angielski, Polski, Turecki, Arabski.",
    price_title: "Cennik",
    price_sub: "Płać tylko za to, czego potrzebujesz. Zacznij bezpłatnie.",
    price1_name: "Przykład PDF dokumentu",
    price1_desc: "Wypełniony przykładowy formularz dla każdego obsługiwanego dokumentu",
    price1_amount: "€4.99",
    price1_note: "za dokument",
    price1_f1: "Wstępnie wypełniony przykład PDF",
    price1_f2: "Plik PDF do pobrania",
    price1_f3: "W Twoim języku",
    price1_f4: "Natychmiastowa dostawa",
    price2_name: "Monitoring Termin",
    price2_desc: "Automatyczny monitoring wizyt w Bürgeramt 24/7",
    price2_badge: "Popularne",
    price2_amount: "€4.99",
    price2_note: "za 24 godziny",
    price2_f1: "Sprawdza co 30 sekund",
    price2_f2: "Natychmiastowe powiadomienie",
    price2_f3: "Bezpośredni link do rezerwacji",
    price2_f4: "Plan 7-dniowy od €14.99",
    price3_name: "Pakiet",
    price3_desc: "PDF dokumentu + 24h monitoring razem",
    price3_amount: "€7.99",
    price3_note: "najlepsza cena · +€3 Termin",
    price3_f1: "Przykład PDF w zestawie",
    price3_f2: "Monitoring 24h w zestawie",
    price3_f3: "Taniej niż oddzielnie",
    price_cta: "Zacznij w Telegramie",
    tg_title: "Otwórz asystenta w Telegramie",
    tg_sub: "Nie masz Telegrama? Pobierz bezpłatnie na dowolne urządzenie.",
    tg_android: "Android",
    tg_ios: "iPhone",
    tg_windows: "Windows",
    tg_mac: "macOS",
    tg_web: "Web",
    tg_note: "Po zainstalowaniu Telegrama kliknij «Otwórz asystenta Telegram».",
    install_hint: "Nie masz Telegrama? Zainstaluj:",
    hero_step1: "1️⃣ Otwiera się bot Telegram",
    hero_step2: "2️⃣ Odpowiedz na kilka pytań",
    hero_step3: "3️⃣ Otrzymaj wypełniony przykład PDF",
    notice_text: "<strong>Informacja:</strong> To narzędzie generuje wstępnie wypełnione przykłady PDF. Nie jest to porada prawna ani oficjalna usługa rządowa. Oficjalne formularze należy składać przez odpowiednie strony rządowe.",
    footer_copy: "© 2026 GermanDocAssist. Wszelkie prawa zastrzeżone.",
    footer_disclaimer: "Te treści nie stanowią porady prawnej. Udostępniane są wyłącznie przykłady PDF.",
    footer_docs: "Dokumenty",
    footer_termin: "Termin",
    footer_legal: "Info",
  },

  tr: {
    nav_home: "Ana Sayfa",
    nav_docs: "Belgeler",
    nav_termin_menu: "Termin",
    nav_anmeldung: "Anmeldung",
    nav_buergergeld: "Bürgergeld",
    nav_kindergeld: "Kindergeld",
    nav_termin: "Termin Berlin",
    nav_faq: "SSS",
    nav_about: "Hakkımızda",
    hero_title: "Alman belgelerini doğru doldurun — <span style='color:#93c5fd'>ilk seferinde.</span>",
    hero_sub: "Anmeldung, Bürgergeld, Kindergeld ve Bürgeramt randevuları için PDF aracı. Kendi dilinizde.",
    hero_trust: "Almanya genelinde göçmenler tarafından kullanılıyor",
    cta_open: "Telegram Asistanını Aç",
    cta_how: "Nasıl çalışır",
    cta_termin: "Termin Takibini Başlat",
    cta_find_termin: "Termin Bul →",
    cta_title: "Başlamaya hazır mısınız?",
    cta_sub: "Telegram botunu açın — ücretsiz deneyin.",
    trust_stat1: "Belgeler",
    trust_stat2: "Diller",
    trust_stat3: "Bulunan randevular",
    trust_badge: "Almanya'daki binlerce göçmen tarafından güvenilir",
    how_title: "Nasıl çalışır",
    how_sub: "Dört basit adım — Almanca bilgisi gerekmez.",
    step1_h: "Belge seçin", step1_p: "15'ten fazla Alman belgesi arasından",
    step2_h: "Formu doldurun", step2_p: "Kendi dilinizde sorulara yanıt verin",
    step3_h: "PDF alın", step3_p: "Doldurulmuş örneği anında indirin",
    step4_h: "Termin takibi", step4_p: "İsteğe bağlı: 7/24 randevu takibi",
    docs_title: "Desteklenen belgeler",
    docs_sub: "Daha fazla bilgi için bir belgeye tıklayın.",
    doc_anmeldung_sub: "Adres kaydı",
    doc_ummeldung_sub: "Adres değişikliği",
    doc_buergergeld_sub: "Sosyal yardım",
    doc_kindergeld_sub: "Çocuk yardımı",
    doc_wohngeld_sub: "Konut yardımı",
    doc_aufenthaltstitel_sub: "Oturma izni",
    doc_familienkasse_sub: "Aile yardımları",
    doc_termin_sub: "Bürgeramt randevu arama",
    why_title: "Göçmenler neden bu aracı kullanıyor",
    why_sub: "Alman bürokrasisi karmaşıktır. Biz onu yönetilebilir hale getiriyoruz.",
    why1_h: "Ret kararından kaçının", why1_p: "Yaygın hatalar başvurmadan önce yakalanır.",
    why2_h: "Karmaşık formları anlayın", why2_p: "Her alan için sade dilde açıklama.",
    why3_h: "Randevudan önce hazırlanın", why3_p: "Her şey hazır Bürgeramt'a gelin.",
    why4_h: "Termin aramaktan zaman kazanın", why4_p: "7/24 izleme — saniyeler içinde bildirim.",
    trust_title: "Binlerce göçmen bu aracı kullanıyor",
    trust_sub: "PDF örnekleri oluşturun ve saatlerce kafa karışıklığından kurtulun.",
    what_title: "Telegram Belge Asistanı Nedir?",
    what_text: "Bu araç, Almanya'daki resmi formların önceden doldurulmuş PDF örneklerini oluşturur. Almanca bilgisi gerekmez.",
    what_li1: "Doğru doldurulmuş örnek formları gösterir",
    what_li2: "Hangi belgeleri getirmeniz gerektiğini açıklar",
    what_li3: "Her form için gerekli tüm alanları gösterir",
    what_li4: "Bürgeramt ziyareti öncesinde hazırlanmanıza yardımcı olur",
    what_li5: "6 dilde çalışır — kendi dilinizde",
    what_cta_h: "Şimdi deneyin — ücretsiz",
    what_cta_p: "Telegram'da asistanı açın ve herhangi bir Alman belgesi hakkında sorun.",
    feat_title: "Bu araç neler yapabilir",
    feat_sub: "Tüm Alman evrak işlemleri için tek araç.",
    feat1_h: "Anmeldung örneği", feat1_p: "Doğru doldurulmuş adres kayıt formu alın.",
    feat2_h: "Bürgergeld başvurusu", feat2_p: "Sosyal yardım formunu anlayın ve doldurun.",
    feat3_h: "Kindergeld formları", feat3_p: "Çocuk yardımı başvurusu için adım adım rehber.",
    feat4_h: "Belge kontrol listesi", feat4_p: "Her randevuya ne getirmeniz gerektiğini bilin.",
    feat5_h: "Termin takibi", feat5_p: "Boş slot için 7/24 otomatik bildirim.",
    feat6_h: "Çok dilli destek", feat6_p: "Ukraynaca, Almanca, İngilizce, Lehçe, Türkçe, Arapça.",
    price_title: "Fiyatlandırma",
    price_sub: "Yalnızca ihtiyacınız olan için ödeyin. Ücretsiz başlayın.",
    price1_name: "Belge PDF Örneği",
    price1_desc: "Desteklenen her belge için doldurulmuş örnek form",
    price1_amount: "€4.99",
    price1_note: "belge başına",
    price1_f1: "Önceden doldurulmuş PDF örneği",
    price1_f2: "İndirilebilir PDF",
    price1_f3: "Kendi dilinizde",
    price1_f4: "Anında teslimat",
    price2_name: "Termin Takibi",
    price2_desc: "7/24 otomatik Bürgeramt randevu izleme",
    price2_badge: "Popüler",
    price2_amount: "€4.99",
    price2_note: "24 saat başına",
    price2_f1: "Her 30 saniyede kontrol",
    price2_f2: "Anlık Telegram bildirimi",
    price2_f3: "Doğrudan rezervasyon bağlantısı",
    price2_f4: "7 günlük plan €14.99'dan",
    price3_name: "Paket",
    price3_desc: "Belge PDF + 24s Termin takibi birlikte",
    price3_amount: "€7.99",
    price3_note: "en iyi değer · +€3 Termin",
    price3_f1: "PDF örneği dahil",
    price3_f2: "24s takip dahil",
    price3_f3: "Ayrı satın almaktan ucuz",
    price_cta: "Telegram'da Başla",
    tg_title: "Asistanı Telegram'da açın",
    tg_sub: "Telegram yok mu? Herhangi bir cihaza ücretsiz indirin.",
    tg_android: "Android",
    tg_ios: "iPhone",
    tg_windows: "Windows",
    tg_mac: "macOS",
    tg_web: "Web",
    tg_note: "Telegram'ı yükledikten sonra \"Telegram Asistanını Aç\" düğmesine dokunun.",
    install_hint: "Telegram yok mu? Yükleyin:",
    hero_step1: "1️⃣ Telegram botu açılır",
    hero_step2: "2️⃣ Birkaç soruyu yanıtlayın",
    hero_step3: "3️⃣ Doldurulmuş PDF örneğini alın",
    notice_text: "<strong>Bilgilendirme:</strong> Bu araç, yalnızca yönlendirme amacıyla önceden doldurulmuş PDF örnekleri oluşturur. Hukuki tavsiye değildir ve resmi bir devlet hizmeti değildir. Resmi formları yetkili devlet sitelerinden gönderin.",
    footer_copy: "© 2026 GermanDocAssist. Tüm hakları saklıdır.",
    footer_disclaimer: "Bu içerikler hukuki tavsiye niteliği taşımaz. Yalnızca PDF örnekleri sunulmaktadır.",
    footer_docs: "Belgeler",
    footer_termin: "Termin",
    footer_legal: "Bilgi",
  },

  ar: {
    nav_home: "الرئيسية",
    nav_docs: "المستندات",
    nav_termin_menu: "المواعيد",
    nav_anmeldung: "Anmeldung",
    nav_buergergeld: "Bürgergeld",
    nav_kindergeld: "Kindergeld",
    nav_termin: "موعد برلين",
    nav_faq: "الأسئلة الشائعة",
    nav_about: "من نحن",
    hero_title: "أعدّ المستندات الألمانية بشكل صحيح — <span style='color:#93c5fd'>من المرة الأولى.</span>",
    hero_sub: "أداة PDF لـ Anmeldung وBürgergeld وKindergeld ومواعيد Bürgeramt. بلغتك.",
    hero_trust: "يستخدمه المهاجرون في جميع أنحاء ألمانيا",
    cta_open: "فتح مساعد تيليجرام",
    cta_how: "كيف يعمل",
    cta_termin: "بدء مراقبة المواعيد",
    cta_find_termin: "← ابحث عن موعد",
    cta_title: "هل أنت مستعد للبدء؟",
    cta_sub: "افتح بوت تيليجرام — مجانًا.",
    trust_stat1: "مستندات",
    trust_stat2: "لغات",
    trust_stat3: "مواعيد وُجدت",
    trust_badge: "موثوق به من قِبل آلاف المهاجرين في ألمانيا",
    how_title: "كيف يعمل",
    how_sub: "أربع خطوات بسيطة — لا يلزم معرفة الألمانية.",
    step1_h: "اختر المستند", step1_p: "من أكثر من 15 مستندًا ألمانيًا",
    step2_h: "أجب على الأسئلة", step2_p: "بلغتك الخاصة",
    step3_h: "احصل على PDF", step3_p: "حمّل المثال المملوء فورًا",
    step4_h: "مراقبة المواعيد", step4_p: "اختياري: مراقبة المواعيد على مدار الساعة",
    docs_title: "المستندات المدعومة",
    docs_sub: "انقر على أي مستند للمزيد من المعلومات.",
    doc_anmeldung_sub: "تسجيل العنوان",
    doc_ummeldung_sub: "تغيير العنوان",
    doc_buergergeld_sub: "الإعانات الاجتماعية",
    doc_kindergeld_sub: "مخصصات الأطفال",
    doc_wohngeld_sub: "إعانة السكن",
    doc_aufenthaltstitel_sub: "تصريح الإقامة",
    doc_familienkasse_sub: "مكتب شؤون الأسرة",
    doc_termin_sub: "حجز موعد في Bürgeramt",
    why_title: "لماذا يستخدم المهاجرون هذه الأداة",
    why_sub: "البيروقراطية الألمانية معقدة. نجعلها قابلة للإدارة.",
    why1_h: "تجنب رفض المستند", why1_p: "الأخطاء الشائعة تُكتشف قبل التقديم.",
    why2_h: "فهم النماذج المعقدة", why2_p: "شرح بسيط لكل حقل.",
    why3_h: "الاستعداد قبل الموعد", why3_p: "تعال إلى Bürgeramt وكل شيء جاهز.",
    why4_h: "توفير الوقت في البحث عن موعد", why4_p: "مراقبة على مدار الساعة — إشعار فوري.",
    trust_title: "آلاف المهاجرين يستخدمون هذه الأداة",
    trust_sub: "أنشئ أمثلة PDF ووفّر ساعات من الارتباك.",
    what_title: "ما هو مساعد وثائق تيليجرام؟",
    what_text: "تُنشئ هذه الأداة أمثلة PDF معبأة مسبقاً للوثائق الرسمية الألمانية. لا حاجة لمعرفة اللغة الألمانية.",
    what_li1: "يعرض نماذج مملوءة بشكل صحيح",
    what_li2: "يشرح المستندات المطلوبة لكل موعد",
    what_li3: "يعرض جميع الحقول المطلوبة لكل نموذج",
    what_li4: "يساعدك على الاستعداد قبل زيارة Bürgeramt",
    what_li5: "يعمل بـ 6 لغات — لغتك الخاصة",
    what_cta_h: "جرّبه الآن — مجانًا",
    what_cta_p: "افتح المساعد في تيليجرام واسأله عن أي وثيقة ألمانية.",
    feat_title: "ما يمكن لهذه الأداة فعله",
    feat_sub: "أداة واحدة لجميع الأوراق الألمانية.",
    feat1_h: "نموذج Anmeldung", feat1_p: "احصل على نموذج تسجيل العنوان مملوءًا بشكل صحيح.",
    feat2_h: "طلب Bürgergeld", feat2_p: "افهم واملأ نموذج الإعانة الاجتماعية.",
    feat3_h: "نماذج Kindergeld", feat3_p: "دليل خطوة بخطوة لطلب مخصص الأطفال.",
    feat4_h: "قائمة المستندات", feat4_p: "اعرف ما تحتاج إحضاره لكل موعد.",
    feat5_h: "مراقبة المواعيد", feat5_p: "إشعارات تلقائية بالمواعيد المتاحة على مدار الساعة.",
    feat6_h: "دعم متعدد اللغات", feat6_p: "أوكراني، ألماني، إنجليزي، بولندي، تركي، عربي.",
    price_title: "الأسعار",
    price_sub: "ادفع فقط لما تحتاجه. ابدأ مجانًا.",
    price1_name: "مثال PDF للوثيقة",
    price1_desc: "نموذج مملوء لأي وثيقة مدعومة",
    price1_amount: "€4.99",
    price1_note: "لكل وثيقة",
    price1_f1: "مثال PDF معبأ مسبقاً",
    price1_f2: "PDF قابل للتنزيل",
    price1_f3: "بلغتك الخاصة",
    price1_f4: "تسليم فوري",
    price2_name: "مراقبة المواعيد",
    price2_desc: "مراقبة تلقائية لمواعيد Bürgeramt على مدار الساعة",
    price2_badge: "الأكثر شعبية",
    price2_amount: "€4.99",
    price2_note: "لكل 24 ساعة",
    price2_f1: "يفحص كل 30 ثانية",
    price2_f2: "إشعار فوري عبر تيليجرام",
    price2_f3: "رابط حجز مباشر",
    price2_f4: "خطة 7 أيام من €14.99",
    price3_name: "الحزمة",
    price3_desc: "PDF الوثيقة + مراقبة 24 ساعة معًا",
    price3_amount: "€7.99",
    price3_note: "أفضل قيمة · +€3 Termin",
    price3_f1: "مثال PDF مضمّن",
    price3_f2: "مراقبة 24 ساعة مضمّنة",
    price3_f3: "أوفر من الشراء المنفصل",
    price_cta: "ابدأ في تيليجرام",
    tg_title: "افتح المساعد في تيليجرام",
    tg_sub: "لا تملك تيليجرام؟ حمّله مجانًا على أي جهاز.",
    tg_android: "أندرويد",
    tg_ios: "آيفون",
    tg_windows: "ويندوز",
    tg_mac: "macOS",
    tg_web: "الويب",
    tg_note: "بعد تثبيت تيليجرام، انقر على «فتح مساعد تيليجرام».",
    install_hint: "ليس لديك تيليجرام؟ ثبّته:",
    hero_step1: "1️⃣ يفتح بوت تيليجرام",
    hero_step2: "2️⃣ أجب على بعض الأسئلة",
    hero_step3: "3️⃣ احصل على مثال PDF معبأ",
    notice_text: "<strong>تنبيه:</strong> تُنشئ هذه الأداة أمثلة PDF معبأة مسبقاً للاستئناس فقط. ليست استشارة قانونية وليست خدمة حكومية رسمية. يرجى تقديم النماذج الرسمية عبر المواقع الحكومية المختصة.",
    footer_copy: "© 2026 GermanDocAssist. جميع الحقوق محفوظة.",
    footer_disclaimer: "لا تشكّل هذه المحتويات استشارة قانونية. يُوفَّر فقط أمثلة PDF.",
    footer_docs: "المستندات",
    footer_termin: "المواعيد",
    footer_legal: "معلومات",
  },
};

// Detect language: localStorage → browser language → fallback "en"
function getLang() {
  const stored = localStorage.getItem("lang");
  if (stored && TRANSLATIONS[stored]) return stored;
  const browser = (navigator.language || "en").slice(0, 2).toLowerCase();
  const MAP = { uk: "ua", ru: "ua" };
  const mapped = MAP[browser] || browser;
  return TRANSLATIONS[mapped] ? mapped : "en";
}

function setLang(lang) {
  if (!TRANSLATIONS[lang]) lang = "en";
  localStorage.setItem("lang", lang);

  document.documentElement.lang = lang;
  document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";

  document.querySelectorAll(".lang-btn").forEach(btn => {
    btn.classList.toggle("active", btn.dataset.lang === lang);
  });

  // Merge global TRANSLATIONS with any page-level overrides (optional)
  const pageT = (window.PAGE_TRANSLATIONS || {})[lang] || {};
  const t = Object.assign({}, TRANSLATIONS[lang], pageT);

  document.querySelectorAll("[data-i18n]").forEach(el => {
    const key = el.dataset.i18n;
    if (t[key] === undefined) return;
    if (el.tagName === "META") {
      el.setAttribute("content", t[key]);
    } else {
      el.innerHTML = t[key];
    }
  });

  document.querySelectorAll(".cta-btn").forEach(btn => {
    if (!btn.dataset.href) btn.dataset.href = btn.href || BOT_URL;
    btn.href = btn.dataset.href || BOT_URL;
  });
}

function _boot() {
  document.querySelectorAll(".lang-btn").forEach(btn => {
    btn.addEventListener("click", () => setLang(btn.dataset.lang));
  });
  setLang(getLang());
}

if (document.readyState === "loading") {
  document.addEventListener("DOMContentLoaded", _boot);
} else {
  _boot();
}
